const data = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://media.istockphoto.com/id/163105191/pl/zdj%C4%99cie/nale%C5%9Bniki-z-jag%C3%B3d-i-syrop-klonowy.jpg?s=612x612&w=0&k=20&c=rUKbyGr27S4pADcSRXXkvdMoC1Kk455lIHVRbRmObMU=',
      desc: "Buttermilk Pancakes is a classic American breakfast dish made from simple ingredients such as flour, sugar, baking powder, egg, butter, and buttermilk.",
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: "https://media.istockphoto.com/id/1140394268/pl/zdj%C4%99cie/sos-szynkowy-tortellini-z-szynk%C4%85-i-parmezanem.jpg?s=612x612&w=0&k=20&c=cGW5Eyq5jfeodqiWYZ3CXDJVzAFW7G3UYEOxUn4UyF8=",
      desc: `An omelette is a delicious and versatile dish made from beaten eggs cooked with various ingredients. The eggs are typically whisked until well combined and then poured into a hot, greased pan.`,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: "https://media.istockphoto.com/id/673747918/pl/zdj%C4%99cie/truskawkowy-koktajl-mleczny-z-bit%C4%85-%C5%9Bmietan%C4%85.jpg?s=612x612&w=0&k=20&c=WRrtjWDxUsDqt6aWMxpLVtan-zwW9wQJjnx-Tf0d0Yw=",
      desc: `A milkshake is a sweet and creamy beverage made by blending together milk, ice cream, and flavorings. The most basic form of a milkshake includes vanilla ice cream, milk, and sugar.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: "https://media.istockphoto.com/id/1220570716/pl/zdj%C4%99cie/jajka-sadzone-s%C5%82oneczne-strony-do-g%C3%B3ry-z-szynk%C4%85.jpg?s=612x612&w=0&k=20&c=xmhutWQSQjl5DDjxHqmODR4y5qcdQ7zU_MjD9aHwfYo=",
      desc: `Two eggs with salmon is a delectable dish that combines the richness of perfectly cooked eggs with the savory flavor of smoked or grilled salmon. The eggs can be prepared in various ways, such as poached, fried, or scrambled. `,
    },
    {
      id: 5,
      title: 'hamburger',
      category: 'lunch',
      price: 22.99,
      img: "https://media.istockphoto.com/id/1647346126/pl/zdj%C4%99cie/pyszny-hamburger-z-mi%C4%99sem-serem-boczkiem-i-sur%C3%B3wk%C4%85.jpg?s=612x612&w=0&k=20&c=mbIb9sXICFr143ptw5xmI9hSdot6DYeSBqDijM4Xe_0=",
      desc: `A hamburger is a classic and iconic American dish that consists of a ground meat patty, typically beef, cooked and served in a sliced bun. `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: "https://media.istockphoto.com/id/1013773136/pl/zdj%C4%99cie/napoj%C3%B3w-i-%C5%BCywno%C5%9Bci.jpg?s=612x612&w=0&k=20&c=gQrlI-et-NudLZOKjuwR-JjOsLeY227JodNgvN1SDAA=",
      desc: `This creamy concoction typically involves blending together vanilla ice cream, milk, and crushed Oreo cookies until smooth and frothy.`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: "https://images.unsplash.com/photo-1511421585906-57a6e6dc3a2f?w=300&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2FuZHZpY2hlcyUyMGZyaWVkfGVufDB8fDB8fHww",
      desc: `A sandwich is a versatile and convenient food item consisting of one or more layers of bread or a bread-like roll, typically with a filling placed between them.`,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: "https://media.istockphoto.com/id/1302436326/pl/zdj%C4%99cie/fast-food-domowe-hamburgery-wo%C5%82owe-na-zabytkowym-drewnianym-tle.jpg?s=612x612&w=0&k=20&c=yAyzqIHGFN9FvC3CjqYjDZJr_TI6nBH8EcWKNIY6nK0=",
      desc: `An American classic burger with seasoned fries is a quintessential dish that captures the essence of comfort food. The burger typically features a juicy beef patty, seasoned with salt and pepper, cooked to perfection on a grill or stovetop.`,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: "https://plus.unsplash.com/premium_photo-1694704419904-08dd41d3a3e7?w=300&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bWlsa3NoYWtlJTIwYm90dGxlfGVufDB8fDB8fHww",
      desc: `A vanilla milkshake is a luscious and creamy beverage that combines the timeless flavor of vanilla with the richness of ice cream and milk. This delightful treat is created by blending together vanilla ice cream, milk, and often a touch of vanilla extract for an extra boost of flavor.`,
    },
  ];
  export default data;